export const dummyPumpData = [
        {
            pumpName: "Pump 1",
            type: "Pump 1",
            areaBlock: "Pump 1",
            latitude: "Pump 1",
            longitude: "Pump 1",
            flowRate: "Pump 1",
            offset: "Pump 1",
            currentPressure: "Pump 1",
            minPressure: "Pump 1",
            maxPressure: "Pump 1",   
        },
        {
    pumpName: "Pump 2",
    type: "Pump 2",
    areaBlock: "Pump 2",
    latitude: "Pump 2",
    longitude: "Pump 2",
    flowRate: "Pump 2",
    offset: "Pump 2",
    currentPressure: "Pump 2",
    minPressure: "Pump 2",
    maxPressure: "Pump 2",},
        {
            pumpName: "Pump 3",
            type: "Pump 3",
            areaBlock: "Pump 3",
            latitude: "Pump 3",
            longitude: "Pump 3",
            flowRate: "Pump 3",
            offset: "Pump 3",
            currentPressure: "Pump 3",
            minPressure: "Pump 3",
            maxPressure: "Pump 3",
        },
        {
            pumpName: "Pump 4",
            type: "Pump 4",
            areaBlock: "Pump 4",
            latitude: "Pump 4",
            longitude: "Pump 4",
            flowRate: "Pump 4",
            offset: "Pump 4",
            currentPressure: "Pump 4",
            minPressure: "Pump 4",
            maxPressure: "Pump 4",
        },
        {
            pumpName: "Pump 5",
            type: "Pump 5",
            areaBlock: "Pump 5",
            latitude: "Pump 5",
            longitude: "Pump 5",
            flowRate: "Pump 5",
            offset: "Pump 5",
            currentPressure: "Pump 5",
            minPressure: "Pump 5",
            maxPressure: "Pump 5",
        },
        {
            pumpName: "Pump 6",
            type: "Pump 6",
            areaBlock: "Pump 6",
            latitude: "Pump 6",
            longitude: "Pump 6",
            flowRate: "Pump 6",
            offset: "Pump 6",
            currentPressure: "Pump 6",
            minPressure: "Pump 6",
            maxPressure: "Pump 6",
        },
        {
            pumpName: "Pump 7",
            type: "Pump 7",
            areaBlock: "Pump 7",
            latitude: "Pump 7",
            longitude: "Pump 7",
            flowRate: "Pump 7",
            offset: "Pump 7",
            currentPressure: "Pump 7",
            minPressure: "Pump 7",
            maxPressure: "Pump 7",
        },
        {
            pumpName: "Pump 8",
            type: "Pump 8",
            areaBlock: "Pump 8",
            latitude: "Pump 8",
            longitude: "Pump 8",
            flowRate: "Pump 8",
            offset: "Pump 8",
            currentPressure: "Pump 8",
            minPressure: "Pump 8",
            maxPressure: "Pump 8",
        },
        {
            pumpName: "Pump 9",
            type: "Pump 9",
            areaBlock: "Pump 9",
            latitude: "Pump 9",
            longitude: "Pump 9",
            flowRate: "Pump 9",
            offset: "Pump 9",
            currentPressure: "Pump 9",
            minPressure: "Pump 9",
            maxPressure: "Pump 9",
        },
        {
            pumpName: "Pump 10",
            type: "Pump 10",
            areaBlock: "Pump 10",
            latitude: "Pump 10",
            longitude: "Pump 10",
            flowRate: "Pump 10",
            offset: "Pump 10",
            currentPressure: "Pump 10",
            minPressure: "Pump 10",
            maxPressure: "Pump 10",
        },
        {
            pumpName: "Pump 11",
            type: "Pump 11",
            areaBlock: "Pump 11",
            latitude: "Pump 11",
            longitude: "Pump 11",
            flowRate: "Pump 11",
            offset: "Pump 11",
            currentPressure: "Pump 11",
            minPressure: "Pump 11",
            maxPressure: "Pump 11",
        },
        {
            pumpName: "Pump 12",
            type: "Pump 12",
            areaBlock: "Pump 12",
            latitude: "Pump 12",
            longitude: "Pump 12",
            flowRate: "Pump 12",
            offset: "Pump 12",
            currentPressure: "Pump 12",
            minPressure: "Pump 12",
            maxPressure: "Pump 12",
        },
        {
            pumpName: "Pump 13",
            type: "Pump 13",
            areaBlock: "Pump 13",
            latitude: "Pump 13",
            longitude: "Pump 13",
            flowRate: "Pump 13",
            offset: "Pump 13",
            currentPressure: "Pump 13",
            minPressure: "Pump 13",
            maxPressure: "Pump 13",
        },
    ];